version: '3.8'

services:
  postgres:
    # TODO: Add here
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql:/var/lib/pgsql/data
    # ports:
    #   - 5432:5432
  backend:
    # TODO: add here
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./:/home/node/app
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/node/app/src
    environment:
      - PORT=3000
      - HOST=postgres
      - DATABASE=mydatabase
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
volumes:
  psql: